name: Send Relevant comment
on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  issues: write

jobs:
  version:
    # if: github.event.pull_request.merged == true
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: vegetables-school/send-relevant-comment-action@v0.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-comment: 'Hello, this is a custom comment'
