name: Send Relevant Comment
on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  issues: write

jobs:
  version:
    # if: github.event.pull_request.merged == true
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: send relevant comment
        uses: vegetables-school/send-relevant-comment-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-comment: 'Hello, This is the trigger comment'
